export const STATE_CHANGE = 'STATE_CHANGE'
export const STATE_SET_SUCCESS = 'STATE_SET_SUCCESS'
export const STATE_SET_REQUEST = 'STATE_SET_REQUEST'
export const STATE_SET_FAILURE = 'STATE_SET_FAILURE'
